services:

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION_TAG}
    container_name: keycloak
    restart: always
    init: true
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '2'
        reservations:
          memory: 512M
          cpus: '1'
    memswap_limit: 2048M
    environment:
      KC_DB_SCHEMA: public
      KC_DB: postgres
      KC_DB_URL_HOST: postgresql_db_keycloak
      KC_DB_PORT: $POSTGRESQL_DB_KEYCLOAK_PORT
      KC_DB_URL_DATABASE: $DB_KEYCLOAK_NAME
      KC_DB_USERNAME: $DB_KEYCLOAK_USERNAME
      KC_DB_PASSWORD: $DB_KEYCLOAK_PASSWORD
      KEYCLOAK_ADMIN: $KEYCLOAK_USERNAME
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_PASSWORD
      KC_HOSTNAME: https://keycloak.host.test.gr/
      KC_HOSTNAME_ADMIN: https://keycloak.host.test.gr/
      KC_PROXY_HEADERS: xforwarded
      KC_TRANSACTION_XA_ENABLED: false
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: false
      KC_HTTP_ENABLED: false
      KC_HTTPS_CERTIFICATE_FILE: /tmp/keycloak.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /tmp/keycloak.key
      KC_LOG_LEVEL: warn
      JAVA_OPTS_APPEND: "-Djava.net.preferIPv4Stack=true"
    ports:
      - "0.0.0.0:$KEYCLOAK_PORT:8443"
    networks:
      - keycloak-network
    volumes:
      - ${LOGS_PATH}/keycloak:/tmp/logs
      - ${CERTIFICATES_PATH}/keycloak.crt:/tmp/keycloak.crt:ro
      - ${CERTIFICATES_PATH}/keycloak.key:/tmp/keycloak.key:ro
    healthcheck:
      test: curl -s https://localhost:8443/realms/master >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
    depends_on:
      postgresql_db_keycloak:
        condition: service_healthy
    command: ["start-dev", "--log=console,file", "--log-file=/tmp/logs/keycloak.log", "--http-port", "7080", "--https-port", "8443"]

  postgresql_db_keycloak:
    image: ghcr.io/giovannicapocci/custom-postgres:${POSTGRES_VERSION_TAG}
    container_name: postgresql_db_keycloak
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "$DB_KEYCLOAK_USERNAME" ]
      interval: 5s
      timeout: 1s
      retries: 5
    restart: always
    init: true
    environment:
      POSTGRES_DB: $DB_KEYCLOAK_NAME
    volumes:
      - ${DATA_BASE_PATH}/postgresql_db_keycloak/data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:$POSTGRESQL_DB_KEYCLOAK_PORT:5432"
    networks:
      - keycloak-network

  reverse-proxy:
    container_name: reverse-proxy
    init: true
    image: nginx:${NGINX_VERSION_TAG}
    user: ${DOCKER_USER}:${DOCKER_GROUP}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
    memswap_limit: 1024M
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CONFIG_BASE_PATH}/nginx.conf:/etc/nginx/nginx.conf
      - ${CONFIG_BASE_PATH}/proxy.conf:/etc/nginx/conf.d/default.conf
      - ${CERTIFICATES_PATH}/nginx.crt:/server-certs/nginx.crt
      - ${CERTIFICATES_PATH}/nginx.key:/server-certs/nginx.key
      - ${LOGS_PATH}/proxy:/tmp/logs
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: keycloak-network
